POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpcnN0X3VzZXIiLCJpZCI6IjY1ODc0MjZkZDdlM2YzOWFkMDBiN2Y2MyIsImlhdCI6MTcwMzM2NzA2OSwiZXhwIjoxNzAzMzcwNjY5fQ.gagwnWn4lRF3noQLshW_5ADf2OHDQjubCQ4ZnMlOUNQ

{
  "title": "Middleware is cool",
  "author": "Lucas Amberg",
  "url": "https://github.com/lucas-amberg",
  "likes": 233
}